### PR TITLE
Fix Invalid dynamic for_each value when applying infrastructure with terragrunt

### PR DESCRIPTION
**Pull request by yyarmoshyk**
## Description
I wanted to re-use your module to deploy sagemaker model, endpoint config and endpoint.
I faced the following errors:
 ```
Error: Invalid dynamic for_each value

  on sagemaker_model.tf line 38, in resource "aws_sagemaker_model" "sagemaker_model":
  38:     for_each = var.sagemaker_model_vpc_config
    |----------------
    | var.sagemaker_model_vpc_config is "[{\"security_group_ids\":[\"sg-aaaaaaaaaa\"],\"subnets\":[\"subnet-bbbbbbbbbbbb\",\"subnet-cccccccccccc\"]}]"
Error: Invalid dynamic for_each value

  on sagemaker_endpoint_configuration.tf line 13, in resource "aws_sagemaker_endpoint_configuration" "sagemaker_endpoint_configuration":
  13:     for_each = var.sagemaker_endpoint_configuration_production_variants
    |----------------
    | var.sagemaker_endpoint_configuration_production_variants is "[{\"initial_instance_count\":1,\"instance_type\":\"ml.g4dn.xlarge\",\"variant_name\":\"variant-name-1\"}]"

Cannot use a string value in for_each. An iterable collection is required.
```

I use terragrunt wrapper to run infrastructure updates. My software versions are the following:
```
Terragrunt v0.28.24
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.48.0
```

I think the problem is in way how terragrunt handles variables and forwards all as strings to terraform, so we need explicit definitions of variable types inside the module variables.

## Motivation and Context
Want to make it work properly with both terragrunt and terraform. 

## Breaking Changes
Does this break backwards compatibility with the current major version? **No**

## How Has This Been Tested?
- I did this change locally and applied the infrastructure update referencing the local version of the code. 
The following `terragrunt.hcl` can be used for testing:
```hcl
terraform {
  source = "github.com/yyarmoshyk/terraform-aws-sagemaker"
}


inputs = {
  name        = "test-sagemaker"
  environment = "test"

  # Sagemaker model
  enable_sagemaker_model             = true
  sagemaker_model_name               = "test-model"
  sagemaker_model_execution_role_arn = "arn:aws:iam::123456789000:role/SageMakerFullAccessRole"

  sagemaker_domain_vpc_id            = "vpc-123456789000"

  sagemaker_model_vpc_config         = [{
    security_group_ids               = ["sg-123456789000"]
    subnets                          = ["subnet-123456789001","subnet-123456789002"]
  }]

  primary_container = [{
    # Image is located in pipeline dev account
    image           = "123456789000.dkr.ecr.us-west-2.amazonaws.com/ecr-image-name"
    model_data_url  = "s3://s3-bucket-name/models.tar.gz"
  }]

  # Sagemaker endpoint config
  enable_sagemaker_endpoint_configuration = true
  sagemaker_endpoint_configuration_name   = "endpoint-config"
  sagemaker_endpoint_configuration_production_variants = [{
    initial_instance_count = 1
    instance_type          = "ml.g4dn.xlarge"
    variant_name           = "variant-name-1"
  }]

  # Sagemaker endpoint
  enable_sagemaker_endpoint = true
  sagemaker_endpoint_name   = "endpoint"

  tags = {
    Provisioner     = "Terraform"
    Environment     = "test"
  }


}
```

### CODE REVIEW

**Comment by SebastianUA** [comment]
Hi @yyarmoshyk 

Thank you for your changes! 
Is it make sense to hardcode type of the vars?

I don't use types inside my modules - https://github.com/SebastianUA/terraform I'm using some functions to execute modules and it works to me :)

**Comment by SebastianUA** [comment]
I mean, you can type any variables when executing a module, something like:

```

module "alb_name_prefix" {
  source      = "../../modules/alb"
  name        = "App-Load-Balancer"
  environment = "staging"

  # Create a new ALB
  enable_alb                     = false
  alb_load_balancer_type         = "application"
  alb_name_prefix                = "alb-"
  alb_security_groups            = ["sg-0cfb43249902af8f2"]
  alb_subnets                    = ["subnet-087ab3540e1a1ace4", "subnet-03212d250885f6986", "subnet-02b0ff71a1d00deb2"]
  alb_internal                   = false
  alb_enable_deletion_protection = false


  tags = tomap({
    "Environment" = "dev",
    "Createdby"   = "Vitaliy Natarov"
  })
}
```

For this case, I used the "tomap" function to set the type vars to map. At this point, you will have better maneuver in the future if you're going to use another type.

**Comment by yyarmoshyk** [comment]
Sebastian, thank you for quick response. The problem appears when I use terragrunt, not pure terraform. I tested tomap and tolist but it didn’t do the trick. Terragrunt forwards all variables as strings and for some reason terraform doesn’t understand the variable type correctly and attempts to process string instead of list(map(string))

**Comment by yyarmoshyk** [comment]
I’ll update  PR tomorrow to reflect only variables that are used in dynamic blocks and cause the issue with terragrunt. This will be more obvious

**Comment by yyarmoshyk** [comment]
@SebastianUA Hello. The file has been updated. I've added type only to the following variables:
- sagemaker_model_vpc_config
- sagemaker_model_primary_container
- sagemaker_model_container
- sagemaker_endpoint_configuration_production_variants

I think that you don't understand what the problem is so let me try to explain one more time.

We use **terragrunt** wrapper to manage infrastructure, **not pure terraform**. This issue doesn't appear with **terraform** (I checked as well). 

I think my team is not the only who is using it because **terragrunt** is really popular among teams who need to manage thousands of resources in dozens of AWS accounts, so I'm pretty sure that one day this issue will be reported again. I'd like to contribute the fix into your module. You did a great job building it and now it is time for others to take part in this work.

Please follow the steps to **reproduce the issue**:
1. [Install terragrunt](https://terragrunt.gruntwork.io/docs/getting-started/install/) (I think that you have terraform installed)
2. Login to your aws account (I think you don't need much details how to do that)
3. Create terragrunt.hcl file with the following contents inside:
```hcl
terraform {
  source = "github.com/SebastianUA/terraform-aws-sagemaker"
}
inputs = {
  name        = "test-sagemaker"
  environment = "test"

  # Sagemaker model
  enable_sagemaker_model             = true
  sagemaker_model_name               = "test-model"
  sagemaker_model_execution_role_arn = "arn:aws:iam::123456789000:role/SageMakerFullAccessRole"

  sagemaker_domain_vpc_id            = "vpc-123456789000"

  sagemaker_model_vpc_config         = [{
    security_group_ids               = ["sg-123456789000"]
    subnets                          = ["subnet-123456789001","subnet-123456789002"]
  }]

  sagemaker_model_primary_container = [{
    # Image is located in pipeline dev account
    image           = "123456789000.dkr.ecr.us-west-2.amazonaws.com/ecr-image-name"
    model_data_url  = "s3://s3-bucket-name/models.tar.gz"
  }]

  # Sagemaker endpoint config
  enable_sagemaker_endpoint_configuration = true
  sagemaker_endpoint_configuration_name   = "endpoint-config"
  sagemaker_endpoint_configuration_production_variants = [{
    initial_instance_count = 1
    instance_type          = "ml.g4dn.xlarge"
    variant_name           = "variant-name-1"
  }]

  # Sagemaker endpoint
  enable_sagemaker_endpoint = true
  sagemaker_endpoint_name   = "endpoint"
}
```
4. Run the following:
```bash
terragrunt plan
```
This will do the backend initialization, install aws provider, etc. and move on with the terraform plan. The fact that I'm using dummy data in variables doesn't really matter because you'll see the following error comming first:
```bash
Error: Invalid dynamic for_each value

  on sagemaker_model.tf line 38, in resource "aws_sagemaker_model" "sagemaker_model":
  38:     for_each = var.sagemaker_model_vpc_config
    |----------------
    | var.sagemaker_model_vpc_config is "[{\"security_group_ids\":[\"sg-0f3519061edf61e71\"],\"subnets\":[\"subnet-0209222931f038ba8\",\"subnet-0998e6d605c3cd9df\"]}]"

Cannot use a string value in for_each. An iterable collection is required.
```
5. If you comment out the block with `sagemaker_model_vpc_config` than you'll see the next error:
```bash
Error: Invalid dynamic for_each value

  on sagemaker_model.tf line 14, in resource "aws_sagemaker_model" "sagemaker_model":
  14:     for_each = var.sagemaker_model_primary_container
    |----------------
    | var.sagemaker_model_primary_container is "[{\"image\":\"851146394722.dkr.ecr.us-west-2.amazonaws.com/lytx-aml-deidentification-deid_service\",\"model_data_url\":\"s3://lytx-machinelearning-model-deploy-anonymizer-dev-oregon-009/models.tar.gz\"}]"

Cannot use a string value in for_each. An iterable collection is required.
```
6. If you replace `sagemaker_model_primary_container` with `sagemaker_model_container` than you'll see the following error:
```bash
Error: Invalid dynamic for_each value

  on sagemaker_model.tf line 26, in resource "aws_sagemaker_model" "sagemaker_model":
  26:     for_each = var.sagemaker_model_container
    |----------------
    | var.sagemaker_model_container is "[{\"image\":\"851146394722.dkr.ecr.us-west-2.amazonaws.com/lytx-aml-deidentification-deid_service\",\"model_data_url\":\"s3://lytx-machinelearning-model-deploy-anonymizer-dev-oregon-009/models.tar.gz\"}]"

Cannot use a string value in for_each. An iterable collection is required.
```
7. Another error appears with `sagemaker_endpoint_configuration_production_variants` and it looks like the following:
```bash
Error: Invalid dynamic for_each value

  on sagemaker_endpoint_configuration.tf line 13, in resource "aws_sagemaker_endpoint_configuration" "sagemaker_endpoint_configuration":
  13:     for_each = var.sagemaker_endpoint_configuration_production_variants
    |----------------
    | var.sagemaker_endpoint_configuration_production_variants is "[{\"initial_instance_count\":1,\"instance_type\":\"ml.g4dn.xlarge\",\"variant_name\":\"variant-name-1\"}]"

Cannot use a string value in for_each. An iterable collection is required.
```

If you update the **source** to `github.com/yyarmoshyk/terraform-aws-sagemaker` (the first terraform{} block) than you'll see that the plan is working fine.

It looks like **terraform** can't process list that is being passed from **terragrunt** and attempts to use it as string. But when we specify the `list` type for variable everything works: terraform expects `list` and receives the `list`

I think all terragrunt users will see this error and it will appear for all variables that are used in dynamic blocks. Complete list is the following:
- sagemaker_app_image_config_file_system_config
- sagemaker_app_image_config_kernel_spec
- sagemaker_code_repository_git_config
- sagemaker_domain_jupyter_server_app_settings
- sagemaker_domain_kernel_gateway_app_settings
- sagemaker_domain_sharing_settings
- sagemaker_domain_tensor_board_app_settings
- sagemaker_endpoint_configuration_production_variants **(included into this PR)**
- sagemaker_feature_group_data_catalog_config
- sagemaker_feature_group_feature_definition
- sagemaker_feature_group_s3_storage_config
- sagemaker_feature_group_security_config
- sagemaker_model_container **(included into this PR)**
- sagemaker_model_primary_container **(included into this PR)**
- sagemaker_model_vpc_config **(included into this PR)**
- sagemaker_user_profile_jupyter_server_app_settings
- sagemaker_user_profile_kernel_gateway_app_settings
- sagemaker_user_profile_sharing_settings
- sagemaker_user_profile_tensor_board_app_settings

Please let me know if you'd like me to add `type = list` to all variables that are used in `dynamic` for_each blocks and make your module functional for terragrunt users too.

Thanks!

**Comment by SebastianUA** [comment]
Hi @yyarmoshyk 

Thank you for the changes. I just merged your PR. I will create a new tag now.

**Comment by SebastianUA** [comment]
Yes, you can add that changes and add types to work better with Terragrunt.

I don't have objections.

**Comment by yyarmoshyk** [comment]
@SebastianUA Could you please create the new tag with the latest changes. Thanks!

**Comment by SebastianUA** [comment]
Sure, @yyarmoshyk - https://github.com/SebastianUA/terraform-aws-sagemaker/releases/tag/v1.2.1

**Pull request merged**
